### ISSUE TITLE
Assignment 1 is ready for grading

### ISSUE THREAD

**Issue by mperezluna** [VIS-2129-F2020/mperezluna-vis#1]
I wasn't sure who to assign this to, so I assigned it to all three of you!

The link to my html file is:
https://vis-2129-f2020.github.io/mperezluna-vis/Assignment-1.html

**Comment by bauranov** [comment]
Thank you for the link! Good work, the charts are simple but very effective.  Do not hesitate to experiment with more unorthodox visualizations. Keep up the good work!
