### ISSUE TITLE
Assignment 3 ready for grading

### ISSUE THREAD

**Issue by mperezluna** [VIS-2129-F2020/mperezluna-vis#3]
Hello, assignment 3 is ready for grading. 

The file is Assignment_3.html. It is linked below.

https://vis-2129-f2020.github.io/mperezluna-vis/Assignment_3.html

**Comment by bauranov** [comment]
Great work! I like your conclusions about the connection between the location of schools and Farmers Markets. All the plots look really good. I look forward to your next assignment.
